name: Build Metabase SQL-HTTP Driver

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for new Metabase release
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/metabase/metabase/releases/latest | jq -r .tag_name)

        echo "Latest Metabase tag: $LATEST_TAG"

        if git rev-parse "$LATEST_TAG" >/dev/null 2>&1; then
          echo "Driver already built for $LATEST_TAG"
          exit 1  # abort workflow
        else
          echo "New Metabase version found: $LATEST_TAG"
          echo "METABASE_VERSION=$LATEST_TAG" >> $GITHUB_ENV
        fi

    - name: Clone Metabase repository
      uses: actions/checkout@v4
      with:
        repository: metabase/metabase
        ref: ${{ env.METABASE_VERSION }}
        path: metabase
        
    - name: Checkout driver code
      uses: actions/checkout@v4
      with:
        path: metabase/modules/drivers/sql-http
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        
    - name: Install Yarn 1.x
      run: |
        npm install -g yarn@1
        yarn --version
        
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@12.3
      with:
        cli: latest
        
    - name: Build driver
      working-directory: ./metabase
      run: |
        git apply ./modules/drivers/sql-http/ci/metabase_drivers_deps.patch
        chmod +x ./bin/build-driver.sh
        ./bin/build-driver.sh sql-http
        
    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: metabase-sql-http-driver
        path: metabase/resources/modules/sql-http.metabase-driver.jar
        if-no-files-found: error
        
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.METABASE_VERSION }}
        name: Release ${{ env.METABASE_VERSION }}
        files: metabase/resources/modules/sql-http.metabase-driver.jar

